apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Troque SEU_USUARIO pelo owner do GitHub (minúsculas)
images:
  - name: healthcare-gateway
    newName: ghcr.io/SEU_USUARIO/healthcare-gateway
    newTag: latest
  - name: healthcare-api-pacientes
    newName: ghcr.io/SEU_USUARIO/healthcare-api-pacientes
    newTag: latest
  - name: healthcare-api-usuarios
    newName: ghcr.io/SEU_USUARIO/healthcare-api-usuarios
    newTag: latest
  - name: healthcare-api-triagem
    newName: ghcr.io/SEU_USUARIO/healthcare-api-triagem
    newTag: latest
