apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: healthcare

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - infra/postgres-init-configmap.yaml
  - infra/postgres.yaml
  - infra/redis.yaml
  - infra/rabbitmq.yaml
  - apps/pacientes.yaml
  - apps/usuarios.yaml
  - apps/triagem.yaml
  - apps/gateway.yaml
  - ingress.yaml
